/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
// Personal libraries
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	RCC_AHB1ENR_t volatile *const pClockAddress = (RCC_AHB1ENR_t*) 0x40023830; // This tells that is a constant pointer (programmer should not change pointer...
	// and volatile refers that volatile data, which means can change
	GPIOx_MODE_t volatile *const pModeRegister = (GPIOx_MODE_t*) 0x40020C00;
	GPIOx_ODR_t volatile *const pOutputData = (GPIOx_ODR_t*) 0x40020C14;

	// 1. Enable the clock for GPOID peripheral in the AHB1EN
	pClockAddress->gpiod_en =  1; // modify the bit address of the clock of the GPIOD that matches the third bit

	// 2. Configure the mode of the IO pint as output
	// make pin 12 (24th bit position) as 1 (SET)
	pModeRegister->pin_12 = 1; // Set the bit 24 to number 1

	// 3. Depending on the value of outputData, turn on/off the led
	while (1) {
		uint8_t hasLEDOn = pOutputData->pin_12; // directly depends on a volatile variable, which reads correclty the variable
		pOutputData->pin_12 = hasLEDOn ? 0 : 1;

		// Do for loop to wait between cycles so it seems that is blinking
		for (uint32_t volatile iterator = 0; iterator < 100000; iterator++); // if not use volatile, compiler knows that nothing happens and will remove loop....
		// causing for aggressive optimizations to not wait for loop because not exist ...
		// volatile tells compiler that variable changes, so it can be optimized
	}
}
